;;; codex-ide-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from codex-ide.el

(let ((loads (get 'codex-ide 'custom-loads))) (if (member '"codex-ide" loads) nil (put 'codex-ide 'custom-loads (cons '"codex-ide" loads)) (put 'tools 'custom-loads (cons 'codex-ide (get 'tools 'custom-loads)))))
(defvar codex-ide-cli-path "codex" "\
Path to the Codex CLI executable.")
(custom-autoload 'codex-ide-cli-path "codex-ide" t)
(defvar codex-ide-buffer-name-function #'codex-ide--default-buffer-name "\
Function used to derive the Codex session buffer name.")
(custom-autoload 'codex-ide-buffer-name-function "codex-ide" t)
(defvar codex-ide-cli-extra-flags "" "\
Additional flags appended to the `codex app-server` command.")
(custom-autoload 'codex-ide-cli-extra-flags "codex-ide" t)
(defvar codex-ide-model nil "\
Optional model name for new or resumed threads.")
(custom-autoload 'codex-ide-model "codex-ide" t)
(defvar codex-ide-session-baseline-prompt "\n- You are a Codex server running inside Emacs.\n- You can use MCP tools to inspect and interact with the running Emacs session.\n- Interpret Emacs terminology as relevant context to the user's request: buffers, regions, windows, point, mark, current file, etc.\n- Do not needlessly use Emacs commands to accomplish agent tasks." "\
Optionally baseline prompt injected into the first real prompt of a new thread.
When set to a non-empty string, `codex-ide' prepends it once as an
`[Emacs session context]' block on the first submitted user turn for a
brand-new thread. Resume and continue flows do not resend it.")
(custom-autoload 'codex-ide-session-baseline-prompt "codex-ide" t)
(defvar codex-ide-buffer-name-prefix "codex" "\
Prefix used when creating Codex session buffer names.")
(custom-autoload 'codex-ide-buffer-name-prefix "codex-ide" t)
(defvar codex-ide-focus-on-open t "\
Whether to focus the Codex window after showing it.")
(custom-autoload 'codex-ide-focus-on-open "codex-ide" t)
(defvar codex-ide-buffer-display-when-approval-required t "\
Whether to display a Codex buffer when it requires approval.
When nil, approval requests are rendered into their Codex buffer and announced
with `message', but a non-visible Codex buffer is not displayed.")
(custom-autoload 'codex-ide-buffer-display-when-approval-required "codex-ide" t)
(defconst codex-ide-display-buffer-options nil "\
Ordered display policy keys for `codex-ide-display-buffer'.

Supported keys are `:reuse-buffer-window', `:reuse-mode-window',
`:other-window', and `:new-window'.")
(defvar codex-ide-session-enable-visual-line-mode t "\
Whether Codex session buffers should enable `visual-line-mode' by default.")
(custom-autoload 'codex-ide-session-enable-visual-line-mode "codex-ide" t)
(defvar codex-ide-approval-policy "on-request" "\
Approval policy for new or resumed Codex threads.")
(custom-autoload 'codex-ide-approval-policy "codex-ide" t)
(defvar codex-ide-sandbox-mode "workspace-write" "\
Sandbox mode for new or resumed Codex threads.")
(custom-autoload 'codex-ide-sandbox-mode "codex-ide" t)
(defvar codex-ide-personality "pragmatic" "\
Personality for new or resumed Codex threads.")
(custom-autoload 'codex-ide-personality "codex-ide" t)
(defvar codex-ide-request-timeout 10 "\
Seconds to wait for synchronous app-server responses.")
(custom-autoload 'codex-ide-request-timeout "codex-ide" t)
(defvar codex-ide-log-max-lines 10000 "\
Maximum number of lines to keep in each Codex log buffer.

When a log buffer grows beyond this limit, older lines are removed from the
top of the buffer.")
(custom-autoload 'codex-ide-log-max-lines "codex-ide" t)
(defvar codex-ide-resume-summary-turn-limit 100 "\
How many recent turns to summarize when resuming a stored thread.")
(custom-autoload 'codex-ide-resume-summary-turn-limit "codex-ide" t)
(autoload 'codex-ide-session-mode "codex-ide" "\
Major mode for Codex app-server session buffers.

(fn)" t)
(autoload 'codex-ide-log-mode "codex-ide" "\
Major mode for Codex IDE log buffers.

(fn)" t)
(autoload 'codex-ide "codex-ide" "\
Start Codex for the current project or directory." t)
(autoload 'codex-ide-continue "codex-ide" "\
Resume the most recent Codex session for the current directory." t)
(autoload 'codex-ide-check-status "codex-ide" "\
Report Codex CLI availability and version." t)
(autoload 'codex-ide-stop "codex-ide" "\
Stop the Codex session associated with the current session buffer." t)
(autoload 'codex-ide-reset-current-session "codex-ide" "\
Stop the current Codex session and start a new one in the same buffer." t)
(autoload 'codex-ide-switch-to-buffer "codex-ide" "\
Show the Codex buffer for the current project." t)
(autoload 'codex-ide-interrupt "codex-ide" "\
Interrupt the active Codex turn for the current project." t)
(autoload 'codex-ide-prompt "codex-ide" "\
Prompt for a Codex message in the minibuffer and submit it from the Codex buffer.
If no live session exists for the current buffer, prompt to start one first." t)
(autoload 'codex-ide-previous-prompt-history "codex-ide" "\
Replace the current prompt with the previous prompt from history." t)
(autoload 'codex-ide-next-prompt-history "codex-ide" "\
Replace the current prompt with the next prompt from history." t)
(autoload 'codex-ide-previous-prompt-line "codex-ide" "\
Jump to the previous user prompt line in the session buffer." t)
(autoload 'codex-ide-next-prompt-line "codex-ide" "\
Jump to the next user prompt line in the session buffer." t)
(autoload 'codex-ide-submit "codex-ide" "\
Submit the current in-buffer prompt to Codex." t)
(register-definition-prefixes "codex-ide" '("codex-ide-"))


;;; Generated autoloads from codex-ide-mcp-bridge.el

(defvar codex-ide-enable-emacs-tool-bridge nil "\
Whether codex-ide should expose Emacs tools to Codex via MCP.

When non-nil, codex-ide starts an MCP bridge server alongside `codex app-server'
and ensures the current Emacs instance is reachable via `emacsclient'.")
(custom-autoload 'codex-ide-enable-emacs-tool-bridge "codex-ide-mcp-bridge" t)
(defvar codex-ide-want-mcp-bridge 'prompt "\
Whether codex-ide should start the Emacs MCP bridge.

When nil, do not start the bridge.  When t, start the bridge without prompting.
When `prompt', ask before enabling the bridge, matching the historical startup
behavior.")
(custom-autoload 'codex-ide-want-mcp-bridge "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-tool-bridge-name "emacs" "\
Name used when registering the Emacs MCP bridge with Codex.")
(custom-autoload 'codex-ide-emacs-tool-bridge-name "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-python-command "python3" "\
Python executable used to launch the standalone Emacs MCP bridge.")
(custom-autoload 'codex-ide-emacs-bridge-python-command "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-emacsclient-command "emacsclient" "\
Path to the `emacsclient' executable used by the bridge.")
(custom-autoload 'codex-ide-emacs-bridge-emacsclient-command "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-script-path nil "\
Path to the standalone Emacs MCP bridge script.

When nil, codex-ide uses `bin/codex-ide-mcp-server.py' from the package directory.")
(custom-autoload 'codex-ide-emacs-bridge-script-path "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-server-name nil "\
Server name the bridge should use with `emacsclient'.

When nil, use the current value of `server-name'.")
(custom-autoload 'codex-ide-emacs-bridge-server-name "codex-ide-mcp-bridge" t)
(defvar codex-ide-suppress-server-start-prompts nil "\
When non-nil, start the Emacs server for the bridge without prompting.

This only affects explicit calls to `codex-ide-mcp-bridge-ensure-server'.  Session
startup now prompts once about enabling the Emacs tool bridge, and enabling the
bridge starts the Emacs server automatically when needed.")
(custom-autoload 'codex-ide-suppress-server-start-prompts "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-startup-timeout 10 "\
Startup timeout in seconds for the Emacs MCP bridge.")
(custom-autoload 'codex-ide-emacs-bridge-startup-timeout "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-tool-timeout 60 "\
Tool-call timeout in seconds for the Emacs MCP bridge.")
(custom-autoload 'codex-ide-emacs-bridge-tool-timeout "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-require-approval nil "\
Whether Emacs MCP bridge tool calls should require user approval.

When nil, `codex-ide' auto-accepts approval requests and approval-like MCP
elicitations that clearly refer to the configured Emacs MCP bridge server or
one of its tools.")
(custom-autoload 'codex-ide-emacs-bridge-require-approval "codex-ide-mcp-bridge" t)
(autoload 'codex-ide-mcp-bridge-request-exempt-from-approval-p "codex-ide-mcp-bridge" "\
Return non-nil when PARAMS describe an Emacs MCP bridge request.

This is used to bypass user confirmation for bridge-originated approval
requests when `codex-ide-emacs-bridge-require-approval' is nil.

(fn PARAMS)")
(autoload 'codex-ide-mcp-bridge-enabled-p "codex-ide-mcp-bridge" "\
Return non-nil when the Emacs MCP bridge should be enabled.")
(autoload 'codex-ide-mcp-bridge-enable "codex-ide-mcp-bridge" "\
Enable the Emacs MCP bridge and ensure the target Emacs server is running.")
(autoload 'codex-ide-mcp-bridge-disable "codex-ide-mcp-bridge" "\
Disable the Emacs MCP bridge.")
(autoload 'codex-ide-mcp-bridge-prompt-to-enable "codex-ide-mcp-bridge" "\
Prompt once to enable the Emacs MCP bridge for session startup.")
(autoload 'codex-ide-mcp-bridge-status "codex-ide-mcp-bridge" "\
Return an alist describing the current Emacs bridge configuration.")
(autoload 'codex-ide-mcp-bridge-ensure-server "codex-ide-mcp-bridge" "\
Ensure the target Emacs server for the bridge is running.")
(autoload 'codex-ide-mcp-bridge-mcp-config-args "codex-ide-mcp-bridge" "\
Return `codex app-server' CLI args that register the Emacs MCP bridge.")
(autoload 'codex-ide-mcp-bridge--json-tool-call "codex-ide-mcp-bridge" "\
Decode JSON PAYLOAD, dispatch a bridge tool call, and return JSON.

(fn PAYLOAD)")
(register-definition-prefixes "codex-ide-mcp-bridge" '("codex-ide-mcp-bridge--"))


;;; Generated autoloads from codex-ide-transient.el

(autoload 'codex-ide-menu "codex-ide-transient" "\
Open the main Codex IDE menu.

(fn)" t)
(autoload 'codex-ide-config-menu "codex-ide-transient" "\
Open the Codex IDE configuration menu.

(fn)" t)
(autoload 'codex-ide-debug-menu "codex-ide-transient" "\
Open a small debug/status menu for Codex IDE.

(fn)" t)
(register-definition-prefixes "codex-ide-transient" '("codex-ide--"))


;;; Generated autoloads from codex-ide-mcp-elicitation.el

(register-definition-prefixes "codex-ide-mcp-elicitation" '("codex-ide-mcp-elicitation-"))


;;; Generated autoloads from codex-ide-mcp-bridge.el

(defvar codex-ide-enable-emacs-tool-bridge nil "\
Whether codex-ide should expose Emacs tools to Codex via MCP.

When non-nil, codex-ide starts an MCP bridge server alongside `codex app-server'
and ensures the current Emacs instance is reachable via `emacsclient'.")
(custom-autoload 'codex-ide-enable-emacs-tool-bridge "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-tool-bridge-name "emacs" "\
Name used when registering the Emacs MCP bridge with Codex.")
(custom-autoload 'codex-ide-emacs-tool-bridge-name "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-python-command "python3" "\
Python executable used to launch the standalone Emacs MCP bridge.")
(custom-autoload 'codex-ide-emacs-bridge-python-command "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-emacsclient-command "emacsclient" "\
Path to the `emacsclient' executable used by the bridge.")
(custom-autoload 'codex-ide-emacs-bridge-emacsclient-command "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-script-path nil "\
Path to the standalone Emacs MCP bridge script.

When nil, codex-ide uses `bin/codex-ide-mcp-server.py' from the package directory.")
(custom-autoload 'codex-ide-emacs-bridge-script-path "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-server-name nil "\
Server name the bridge should use with `emacsclient'.

When nil, use the current value of `server-name'.")
(custom-autoload 'codex-ide-emacs-bridge-server-name "codex-ide-mcp-bridge" t)
(defvar codex-ide-suppress-server-start-prompts nil "\
When non-nil, start the Emacs server for the bridge without prompting.

This only affects explicit calls to `codex-ide-mcp-bridge-ensure-server'.  Session
startup now prompts once about enabling the Emacs tool bridge, and enabling the
bridge starts the Emacs server automatically when needed.")
(custom-autoload 'codex-ide-suppress-server-start-prompts "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-startup-timeout 10 "\
Startup timeout in seconds for the Emacs MCP bridge.")
(custom-autoload 'codex-ide-emacs-bridge-startup-timeout "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-tool-timeout 60 "\
Tool-call timeout in seconds for the Emacs MCP bridge.")
(custom-autoload 'codex-ide-emacs-bridge-tool-timeout "codex-ide-mcp-bridge" t)
(defvar codex-ide-emacs-bridge-require-approval nil "\
Whether Emacs MCP bridge tool calls should require user approval.

When nil, `codex-ide' auto-accepts approval requests and approval-like MCP
elicitations that clearly refer to the configured Emacs MCP bridge server or
one of its tools.")
(custom-autoload 'codex-ide-emacs-bridge-require-approval "codex-ide-mcp-bridge" t)
(autoload 'codex-ide-mcp-bridge-request-exempt-from-approval-p "codex-ide-mcp-bridge" "\
Return non-nil when PARAMS describe an Emacs MCP bridge request.

This is used to bypass user confirmation for bridge-originated approval
requests when `codex-ide-emacs-bridge-require-approval' is nil.

(fn PARAMS)")
(autoload 'codex-ide-mcp-bridge-enabled-p "codex-ide-mcp-bridge" "\
Return non-nil when the Emacs MCP bridge should be enabled.")
(autoload 'codex-ide-mcp-bridge-enable "codex-ide-mcp-bridge" "\
Enable the Emacs MCP bridge and ensure the target Emacs server is running.")
(autoload 'codex-ide-mcp-bridge-disable "codex-ide-mcp-bridge" "\
Disable the Emacs MCP bridge.")
(autoload 'codex-ide-mcp-bridge-prompt-to-enable "codex-ide-mcp-bridge" "\
Prompt once to enable the Emacs MCP bridge for session startup.")
(autoload 'codex-ide-mcp-bridge-status "codex-ide-mcp-bridge" "\
Return an alist describing the current Emacs bridge configuration.")
(autoload 'codex-ide-mcp-bridge-ensure-server "codex-ide-mcp-bridge" "\
Ensure the target Emacs server for the bridge is running.")
(autoload 'codex-ide-mcp-bridge-mcp-config-args "codex-ide-mcp-bridge" "\
Return `codex app-server' CLI args that register the Emacs MCP bridge.")
(autoload 'codex-ide-mcp-bridge--json-tool-call "codex-ide-mcp-bridge" "\
Decode JSON PAYLOAD, dispatch a bridge tool call, and return JSON.

(fn PAYLOAD)")
(register-definition-prefixes "codex-ide-mcp-bridge" '("codex-ide-mcp-bridge--"))


;;; Generated autoloads from codex-ide-session-buffer-list.el

(autoload 'codex-ide-session-buffer-list "codex-ide-session-buffer-list" "\
Show a tabulated list of live Codex session buffers." t)
(register-definition-prefixes "codex-ide-session-buffer-list" '("codex-ide-session-buffer-list-"))


;;; Generated autoloads from codex-ide-session-list.el

(register-definition-prefixes "codex-ide-session-list" '("codex-ide-session-list-"))


;;; Generated autoloads from codex-ide-session-thread-list.el

(autoload 'codex-ide-session-thread-list "codex-ide-session-thread-list" "\
Show a tabulated list of stored Codex threads for the current workspace." t)
(register-definition-prefixes "codex-ide-session-thread-list" '("codex-ide-session-thread-list-"))


;;; Generated autoloads from codex-ide-delete-session-thread.el

(autoload 'codex-ide-delete-session-thread "codex-ide-delete-session-thread" "\
Delete Codex THREAD-ID from the active `CODEX_HOME`.

This command relies on current Codex internal storage details under
`CODEX_HOME`, specifically the persisted rollout files under the sessions
directory.  That makes it more fragile than the rest of codex-ide, which
primarily uses the public app-server API.  If Codex adds an officially
supported thread deletion API, this implementation should be replaced to use
that instead.

If a live session buffer is attached to THREAD-ID, prompt before tearing down
that session and then remove the persisted thread data from disk.

(fn THREAD-ID)" t)
(register-definition-prefixes "codex-ide-delete-session-thread" '("codex-ide--"))


;;; Generated autoloads from codex-ide-core.el

(register-definition-prefixes "codex-ide-core" '("codex-ide-" "make-codex-ide-session"))


;;; Generated autoloads from codex-ide-renderer.el

(register-definition-prefixes "codex-ide-renderer" '("codex-ide-"))


;;; Generated autoloads from codex-ide-debug-info.el

(autoload 'codex-ide-show-debug-info "codex-ide-debug-info" "\
Show a minibuffer summary of live Codex IDE session state." t)
(register-definition-prefixes "codex-ide-debug-info" '("codex-ide-debug-info--"))

;;; End of scraped data

(provide 'codex-ide-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; codex-ide-autoloads.el ends here
