;;; codex-ide-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from codex-ide.el

(let ((loads (get 'codex-ide 'custom-loads))) (if (member '"codex-ide" loads) nil (put 'codex-ide 'custom-loads (cons '"codex-ide" loads)) (put 'tools 'custom-loads (cons 'codex-ide (get 'tools 'custom-loads)))))
(defvar codex-ide-cli-path "codex" "\
Path to the Codex CLI executable.")
(custom-autoload 'codex-ide-cli-path "codex-ide" t)
(defvar codex-ide-buffer-name-function #'codex-ide--default-buffer-name "\
Function used to derive the Codex session buffer name.")
(custom-autoload 'codex-ide-buffer-name-function "codex-ide" t)
(defvar codex-ide-cli-extra-flags "" "\
Additional flags appended to the `codex app-server` command.")
(custom-autoload 'codex-ide-cli-extra-flags "codex-ide" t)
(defvar codex-ide-model nil "\
Optional model name for new or resumed threads.")
(custom-autoload 'codex-ide-model "codex-ide" t)
(defvar codex-ide-buffer-name-prefix "codex" "\
Prefix used when creating Codex session buffer names.")
(custom-autoload 'codex-ide-buffer-name-prefix "codex-ide" t)
(defvar codex-ide-use-side-window nil "\
Whether to display Codex buffers in a side window.")
(custom-autoload 'codex-ide-use-side-window "codex-ide" t)
(defvar codex-ide-window-side 'right "\
Side of the frame where Codex should be displayed.")
(custom-autoload 'codex-ide-window-side "codex-ide" t)
(defvar codex-ide-window-width 90 "\
Width of the Codex side window when using left or right placement.")
(custom-autoload 'codex-ide-window-width "codex-ide" t)
(defvar codex-ide-window-height 20 "\
Height of the Codex side window when using top or bottom placement.")
(custom-autoload 'codex-ide-window-height "codex-ide" t)
(defvar codex-ide-focus-on-open t "\
Whether to focus the Codex window after showing it.")
(custom-autoload 'codex-ide-focus-on-open "codex-ide" t)
(defvar codex-ide-session-enable-visual-line-mode t "\
Whether Codex session buffers should enable `visual-line-mode' by default.")
(custom-autoload 'codex-ide-session-enable-visual-line-mode "codex-ide" t)
(defvar codex-ide-approval-policy "on-request" "\
Approval policy for new or resumed Codex threads.")
(custom-autoload 'codex-ide-approval-policy "codex-ide" t)
(defvar codex-ide-sandbox-mode "workspace-write" "\
Sandbox mode for new or resumed Codex threads.")
(custom-autoload 'codex-ide-sandbox-mode "codex-ide" t)
(defvar codex-ide-personality "pragmatic" "\
Personality for new or resumed Codex threads.")
(custom-autoload 'codex-ide-personality "codex-ide" t)
(defvar codex-ide-request-timeout 10 "\
Seconds to wait for synchronous app-server responses.")
(custom-autoload 'codex-ide-request-timeout "codex-ide" t)
(defvar codex-ide-log-max-lines 10000 "\
Maximum number of lines to keep in each Codex log buffer.

When a log buffer grows beyond this limit, older lines are removed from the
top of the buffer.")
(custom-autoload 'codex-ide-log-max-lines "codex-ide" t)
(defvar codex-ide-include-active-buffer-context 'when-changed "\
How `codex-ide' should include Emacs active-buffer context in prompts.
When set to `when-changed', include the active file context only when it has
changed since the last prompt sent to that session.
When set to `always', include the active file context on every prompt.
When nil, never include active-buffer context automatically.")
(custom-autoload 'codex-ide-include-active-buffer-context "codex-ide" t)
(autoload 'codex-ide-session-mode "codex-ide" "\
Major mode for Codex app-server session buffers.

(fn)" t)
(autoload 'codex-ide-log-mode "codex-ide" "\
Major mode for Codex IDE log buffers.

(fn)" t)
(autoload 'codex-ide "codex-ide" "\
Start Codex for the current project or directory." t)
(autoload 'codex-ide-resume "codex-ide" "\
Resume a Codex session using an Emacs picker." t)
(autoload 'codex-ide-continue "codex-ide" "\
Resume the most recent Codex session for the current directory." t)
(autoload 'codex-ide-check-status "codex-ide" "\
Report Codex CLI availability and version." t)
(autoload 'codex-ide-stop "codex-ide" "\
Stop the Codex session for the current project or directory." t)
(autoload 'codex-ide-switch-to-buffer "codex-ide" "\
Show the Codex buffer for the current project." t)
(autoload 'codex-ide-list-sessions "codex-ide" "\
List active Codex sessions and switch to the selected one." t)
(autoload 'codex-ide-interrupt "codex-ide" "\
Interrupt the active Codex turn for the current project." t)
(autoload 'codex-ide-prompt "codex-ide" "\
Prompt for a Codex message in the minibuffer and submit it from the Codex buffer.
If no live session exists for the current buffer, prompt to start one first." t)
(autoload 'codex-ide-previous-prompt-history "codex-ide" "\
Replace the current prompt with the previous prompt from history." t)
(autoload 'codex-ide-next-prompt-history "codex-ide" "\
Replace the current prompt with the next prompt from history." t)
(autoload 'codex-ide-previous-prompt-line "codex-ide" "\
Jump to the previous user prompt line in the session buffer." t)
(autoload 'codex-ide-next-prompt-line "codex-ide" "\
Jump to the next user prompt line in the session buffer." t)
(autoload 'codex-ide-submit "codex-ide" "\
Submit the current in-buffer prompt to Codex." t)
(autoload 'codex-ide-send-active-buffer-context "codex-ide" "\
Send the currently tracked Emacs buffer context to the Codex session." t)
(autoload 'codex-ide-toggle "codex-ide" "\
Toggle visibility of the Codex window for the current project." t)
(autoload 'codex-ide-toggle-recent "codex-ide" "\
Toggle the most recently used Codex window globally." t)
(register-definition-prefixes "codex-ide" '("codex-ide-" "make-codex-ide-session"))


;;; Generated autoloads from codex-ide-bridge.el

(defvar codex-ide-enable-emacs-tool-bridge nil "\
Whether codex-ide should expose Emacs tools to Codex via MCP.

When non-nil, codex-ide starts an MCP bridge server alongside `codex app-server'
and ensures the current Emacs instance is reachable via `emacsclient'.")
(custom-autoload 'codex-ide-enable-emacs-tool-bridge "codex-ide-bridge" t)
(defvar codex-ide-emacs-tool-bridge-name "emacs" "\
Name used when registering the Emacs MCP bridge with Codex.")
(custom-autoload 'codex-ide-emacs-tool-bridge-name "codex-ide-bridge" t)
(defvar codex-ide-emacs-bridge-python-command "python3" "\
Python executable used to launch the standalone Emacs MCP bridge.")
(custom-autoload 'codex-ide-emacs-bridge-python-command "codex-ide-bridge" t)
(defvar codex-ide-emacs-bridge-emacsclient-command "emacsclient" "\
Path to the `emacsclient' executable used by the bridge.")
(custom-autoload 'codex-ide-emacs-bridge-emacsclient-command "codex-ide-bridge" t)
(defvar codex-ide-emacs-bridge-script-path nil "\
Path to the standalone Emacs MCP bridge script.

When nil, codex-ide uses `codex-ide-mcp.py' from the package directory.")
(custom-autoload 'codex-ide-emacs-bridge-script-path "codex-ide-bridge" t)
(defvar codex-ide-emacs-bridge-server-name nil "\
Server name the bridge should use with `emacsclient'.

When nil, use the current value of `server-name'.")
(custom-autoload 'codex-ide-emacs-bridge-server-name "codex-ide-bridge" t)
(defvar codex-ide-suppress-server-start-prompts nil "\
When non-nil, start the Emacs server for the bridge without prompting.

This only affects explicit calls to `codex-ide-bridge-ensure-server'.  Session
startup now prompts once about enabling the Emacs tool bridge, and enabling the
bridge starts the Emacs server automatically when needed.")
(custom-autoload 'codex-ide-suppress-server-start-prompts "codex-ide-bridge" t)
(defvar codex-ide-emacs-bridge-command-whitelist '(save-buffer) "\
Interactive Emacs commands exposed through the MCP bridge.

Each entry should name an interactive command that can safely run without
prompting for extra input.")
(custom-autoload 'codex-ide-emacs-bridge-command-whitelist "codex-ide-bridge" t)
(defvar codex-ide-emacs-bridge-allow-eval nil "\
Whether to expose an unrestricted Elisp eval tool to Codex.")
(custom-autoload 'codex-ide-emacs-bridge-allow-eval "codex-ide-bridge" t)
(defvar codex-ide-emacs-bridge-startup-timeout 10 "\
Startup timeout in seconds for the Emacs MCP bridge.")
(custom-autoload 'codex-ide-emacs-bridge-startup-timeout "codex-ide-bridge" t)
(defvar codex-ide-emacs-bridge-tool-timeout 60 "\
Tool-call timeout in seconds for the Emacs MCP bridge.")
(custom-autoload 'codex-ide-emacs-bridge-tool-timeout "codex-ide-bridge" t)
(autoload 'codex-ide-bridge-enabled-p "codex-ide-bridge" "\
Return non-nil when the Emacs MCP bridge should be enabled.")
(autoload 'codex-ide-bridge-enable "codex-ide-bridge" "\
Enable the Emacs MCP bridge and ensure the target Emacs server is running.")
(autoload 'codex-ide-bridge-disable "codex-ide-bridge" "\
Disable the Emacs MCP bridge.")
(autoload 'codex-ide-bridge-prompt-to-enable "codex-ide-bridge" "\
Prompt once to enable the Emacs MCP bridge for session startup.")
(autoload 'codex-ide-bridge-status "codex-ide-bridge" "\
Return an alist describing the current Emacs bridge configuration.")
(autoload 'codex-ide-bridge-ensure-server "codex-ide-bridge" "\
Ensure the target Emacs server for the bridge is running.")
(autoload 'codex-ide-bridge-mcp-config-args "codex-ide-bridge" "\
Return `codex app-server' CLI args that register the Emacs MCP bridge.")
(autoload 'codex-ide-bridge-dispatch-json "codex-ide-bridge" "\
Dispatch PAYLOAD, a JSON bridge request, and return a JSON response string.

(fn PAYLOAD)")
(register-definition-prefixes "codex-ide-bridge" '("codex-ide-bridge--"))


;;; Generated autoloads from codex-ide-transient.el

(autoload 'codex-ide-menu "codex-ide-transient" "\
Open the main Codex IDE menu.

(fn)" t)
(autoload 'codex-ide-config-menu "codex-ide-transient" "\
Open the Codex IDE configuration menu.

(fn)" t)
(autoload 'codex-ide-debug-menu "codex-ide-transient" "\
Open a small debug/status menu for Codex IDE.

(fn)" t)
(register-definition-prefixes "codex-ide-transient" '("codex-ide--"))


;;; End of scraped data

(provide 'codex-ide-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; codex-ide-autoloads.el ends here
